pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            stages {
                stage('Installation dependances') {
                    steps {
                        dir('safari_front') {
                            sh 'npm install'
                        }
                    }
                }

                stage('Analyse Sonar') {
                    steps {
                        dir('safari_front') {
                            withSonarQubeEnv('SonarQube') {
                                sh './node_modules/.bin/sonar-scanner -Dsonar.projectKey=safari_front'
                            }
                        }
                    }
                }

                stage('Build Angular') {
                    steps {
                        dir('safari_front') {
                            sh './node_modules/.bin/ng build'
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('safari_front') {
                    sh 'docker build -t poketeam/safari:angular .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                dir('') {
                    sh 'docker compose up -d --no-deps --build angular'
                }
            }
        }
    }
}
