pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        
                        --network devops
                    '''
                    reuseNode true
                }
            }

            stages {
                stage('Installation dependances') {
                    steps {
                        dir('safari_front') {
                            sh 'npm install'
                        }
                    }
                }

                stage('Analyse Sonar') {
                    steps {
                        dir('safari_front') {
                            withSonarQubeEnv('SonarQube') {
                                sh '''
                                    chmod +x ./node_modules/.bin/sonar-scanner
                                    ./node_modules/.bin/sonar-scanner \
                                        -Dsonar.projectKey=safari_front \
                                        -Dsonar.sources=src \
                                        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
                                '''
                            }
                        }
                    }

                }
                stage('Build Angular') {
                        steps {
                            dir('safari-front') {
                                sh './node_modules/.bin/ng build'
                            }
                        }
                    }
                }
        }

        stage('Docker Build') {
            steps {
                dir('safari_front') {
                    sh 'docker build -t poketeam/safari:angular .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                sh 'docker compose up -d --no-deps --build angular'
            }
        }
    }
}
