pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        -u root
                        --network devops
                    '''
                    reuseNode true
                }
            }

            stages {
                stage('Installation dependances') {
                    steps {
                        dir('safari_front') {
                            sh 'npm install'
                        }
                    }
                }
            }
        }

        stage('Analyse Sonar') {
            agent {
                docker {
                    image 'sonarsource/sonar-scanner-cli:latest'
                    args '--network devops'
                    reuseNode true
                }
            }
            steps {
                dir('safari_front') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                          sonar-scanner \
                            -Dsonar.projectKey=safari_front \
                            -Dsonar.sources=src \
                            -Dsonar.exclusions="**/*.spec.ts,**/node_modules/**,dist/**"
                        '''
                    }
                }
            }
        }

        stage('Build Angular') {
            agent {
                docker {
                    image 'node:lts-bullseye'
                    args '''
                        -v $HOME/.npm:/root/.npm:z
                        -u root
                        --network devops
                    '''
                    reuseNode true
                }
            }
            steps {
                dir('safari_front') {
                    sh 'npm run build -- --configuration production'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('safari_front') {
                    sh 'docker build -t poketeam/safari:angular .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                sh 'docker compose up -d --no-deps --build angular'
            }
        }
    }
}
